#!/usr/bin/env bash
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    # Bug/issue - https://github.com/aspiers/stow/issues/65
    stow -D $folder 2>&1 | grep -v "BUG in find_stowed_path"
    stow $folder
done
popd
