# Common Packages: https://github.com/joelparkerhenderson/brewfile

# Preflight
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap "buo/cask-upgrade"
tap 'cloudfoundry/tap'
tap 'starkandwayne/cf'
tap 'vmware-tanzu/carvel'
tap 'vmware-tanzu/tanzu'
tap 'kryptco/tap/kr'

# Shell
brew 'zsh'
brew 'pkg-config', link: true
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'tmate'

# Editors
brew 'bat'
brew 'less'
brew 'most'
brew 'vim'
brew 'nvim'

# Downloaders
brew 'curl', link: true
brew 'wget'

# Version control
brew 'git'
brew 'git-flow'

# GNU
brew 'gnu-sed'
brew 'watch'

# System
brew 'gpg'
brew 'openssl'
brew 'pkg-config'
brew 'fd'
brew 'fzf'
brew 'zoxide'

# Command line system operator helpers
brew 'eg-examples'
brew 'tldr'
brew 'howdoi'

# File handling
brew 'unzip'
brew 'gzip'

# File synchronization
brew 'rsync'

# Text search
brew 'ripgrep'
brew 'grep'
brew 'ag'
brew 'jq'
brew 'yq'

# Dev
brew 'shellcheck'

# Networking
brew 'netcat'
brew 'prettyping'
brew 'nmap'
brew 'certbot'

# Languages
brew 'go'
brew 'openjdk'
brew 'gradle'
brew 'maven'
brew 'node'
brew 'python'
brew 'python3'

# Cloud
brew 'azure-cli'
brew 'awscli'

# Provisioning
brew 'terraform'
brew 'ansible'

# Containeriztion
brew 'docker-compose'

# Orchestration
brew 'kubectl'
brew 'minikube'

# CloudFoundry / BOSH
brew 'bbl'
brew 'bosh-cli'
brew 'cloudfoundry/tap/cf-cli@6'
brew 'cloudfoundry/tap/credhub-cli'
brew 'spruce'

# VMWare Carvel
brew 'ytt'
brew 'kbld'
brew 'kapp'
brew 'kwt'
brew 'imgpkg'
brew 'vendir'

# Everything else (custom)
brew 'romkatv/powerlevel10k/powerlevel10k'
brew 'buildpacks/tap/pack'
brew 'octant'
brew 'govc'
brew 'krew'
brew 'kube-ps1'
brew 'kubectx'
brew 'k9s'
brew 'k6'
brew 'helm'
brew 'helmfile'
brew 'kind'
brew 'hadolint'
brew 'stow'
brew 'tanzu-community-edition'
brew 'velero'
brew 'jenv'
brew 'minio/stable/mc'
brew 'om'
brew 'derailed/popeye/popeye'
brew 'pygments'
brew 'fpp'
brew 'lima'
brew 'libyaml'
brew 'yamllint'
brew 'tree'
brew 'ack'
brew 'base64'
brew 'zsh-completions'
brew 'kr'

# Mac App Store
brew 'mas' # mas search <name>
#mas "Apple Configurator 2", id: 1037126344
#mas "Brightness Slider", id: 456624497
#mas "Color Picker", id: 641027709
#mas "Expressions", id: 913158085
#mas "Telegram", id: 747648890

# Casks
cask 'font-hack-nerd-font'
cask 'fly'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'discord'
cask 'slack'
cask 'iterm2'
cask 'atom'
cask 'sublime-text'
cask 'vlc'
cask 'alfred'
cask 'bartender'
cask 'skype'
cask 'spotify'
cask 'karabiner-elements'
cask 'zoom'
cask 'postman'
cask 'dash'
cask 'macdown'
cask 'google-cloud-sdk'
cask 'virtualbox'
cask 'vagrant'
cask 'docker'
cask 'vagrant-manager'
cask 'shiftit'
cask 'visual-studio-code'
cask 'flycut'
cask 'webex-meetings'
cask 'microsoft-teams'
cask 'powershell'
cask 'lens'
